service: serverless-ethers
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  timeout: 30
  environment:
    CHAIN_ID: 111
    URL: "https://explorer.testnet.veladev.net/rpc"
    # DEFAULT_GAS_PRICE: 60000000000
    # MNEMONIC: ""
    # FROM_ADDRESS: ""
    # SLACK_HOOK_URL: ""

functions:
  exec:
    handler: functions/exec.handler
    events:
      - schedule: rate(1 minute)
      # - schedule: cron(0 12 * * ? *) # 12PM UTC

plugins:
  - serverless-offline
  - serverless-offline-scheduler
